apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-hls
  labels:
    {{- include "mediamtx.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "mediamtx.labels" . | nindent 4 }}
  ports:
    - name: hls
      port: {{ .Values.hls.service.port }}
      targetPort: hls
